version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TZ: "Europe/Berlin"
      MEMORY: "4G"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /home/harry/minecraft:/data